# This workflow is used to update the build status badge in the README file.
name: CI Workflow

on:
  push:
    branches:
      - 'release/next'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Set up JDK 8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 8

      - name: Build with Maven
        run: mvn -B package verify
