name: CI Workflow

on:
  push:
    branches-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Set up JDK 8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 8

      - name: Build with Maven
        run: mvn -B package verify
